class ServerParam: #TODO spicfic TYPES and change them
    def __init__(self, dic):
        self._audio_cut_dist = None
        self._back_passes = None
        self._ball_accel_max = None
        self._ball_decay = None
        self._ball_rand = None
        self._ball_size = None
        self._ball_speed_max = None
        self._ball_weight = None
        self._catch_ban_cycle = None
        self._catch_probability = None
        self._catchable_area_l = None
        self._catchable_area_w = None
        self._ckick_margin = None
        self._clang_advice_win = None
        self._clang_define_win = None
        self._clang_del_win = None
        self._clang_info_win = None
        self._clang_mess_delay = None
        self._clang_mess_per_cycle = None
        self._clang_meta_win = None
        self._clang_rule_win = None
        self._clang_win_size = None
        self._coach = None
        self._coach_port = None
        self._coach_w_referee = None
        self._control_radius = None
        self._dash_power_rate = None
        self._drop_ball_time = None
        self._effort_dec = None
        self._effort_dec_thr = None
        self._effort_inc = None
        self._effort_inc_thr = None
        self._effort_init = None
        self._effort_min = None
        self._forbid_kick_off_offside = None
        self._free_kick_faults = None
        self._freeform_send_period = None
        self._freeform_wait_period = None
        self._fullstate_l = None
        self._fullstate_r = None
        self._game_log_compression = None
        self._game_log_dated = None
        self._game_log_dir = None
        self._game_log_fixed = None
        self._game_log_fixed_name = None
        self._game_log_version = None
        self._game_logging = None
        self._goal_width = None
        self._goalie_max_moves = None
        self._half_time = None
        self._hear_decay = None
        self._hear_inc = None
        self._hear_max = None
        self._inertia_moment = None
        self._kick_power_rate = None
        self._kick_rand = None
        self._kick_rand_factor_l = None
        self._kick_rand_factor_r = None
        self._kickable_margin = None
        self._landmark_file = None
        self._log_date_format = None
        self._log_times = None
        self._max_goal_kicks = None
        self._maxmoment = None
        self._maxneckang = None
        self._maxneckmoment = None
        self._maxpower = None
        self._minmoment = None
        self._minneckang = None
        self._minneckmoment = None
        self._minpower = None
        self._offside_active_area_size = None
        self._offside_kick_margin = None
        self._olcoach_port = None
        self._old_coach_hear = None
        self._player_accel_max = None
        self._player_decay = None
        self._player_rand = None
        self._player_size = None
        self._player_speed_max = None
        self._player_weight = None
        self._point_to_ban = None
        self._point_to_duration = None
        self._port = None
        self._prand_factor_l = None
        self._prand_factor_r = None
        self._profile = None
        self._proper_goal_kicks = None
        self._quantize_step = None
        self._quantize_step_l = None
        self._record_messages = None
        self._recover_dec = None
        self._recover_dec_thr = None
        self._recover_min = None
        self._recv_step = None
        self._say_coach_cnt_max = None
        self._say_coach_msg_size = None
        self._say_msg_size = None
        self._send_comms = None
        self._send_step = None
        self._send_vi_step = None
        self._sense_body_step = None
        self._simulator_step = None
        self._slow_down_factor = None
        self._slowness_on_top_for_left_team = None
        self._slowness_on_top_for_right_team = None
        self._stamina_inc_max = None
        self._stamina_max = None
        self._start_goal_l = None
        self._start_goal_r = None
        self._stopped_ball_vel = None
        self._synch_micro_sleep = None
        self._synch_mode = None
        self._synch_offset = None
        self._tackle_back_dist = None
        self._tackle_cycles = None
        self._tackle_dist = None
        self._tackle_exponent = None
        self._tackle_power_rate = None
        self._tackle_width = None
        self._team_actuator_noise = None
        self._text_log_compression = None
        self._text_log_dated = None
        self._text_log_dir = None
        self._text_log_fixed = None
        self._text_log_fixed_name = None
        self._text_logging = None
        self._use_offside = None
        self._verbose = None
        self._visible_angle = None
        self._visible_distance = None
        self._wind_ang = None
        self._wind_dir = None
        self._wind_force = None
        self._wind_none = None
        self._wind_rand = None
        self._wind_random = None

    def set_data(self,dic):
        self._audio_cut_dist = dic["server_param"]["audio_cut_dist "]
        self._back_passes = dic["server_param"]["back_passes "]
        self._ball_accel_max = dic["server_param"]["ball_accel_max "]
        self._ball_decay = dic["server_param"]["ball_decay "]
        self._ball_rand = dic["server_param"]["ball_rand "]
        self._ball_size = dic["server_param"]["ball_size "]
        self._ball_speed_max = dic["server_param"]["ball_speed_max "]
        self._ball_weight = dic["server_param"]["ball_weight "]
        self._catch_ban_cycle = dic["server_param"]["catch_ban_cycle "]
        self._catch_probability = dic["server_param"]["catch_probability "]
        self._catchable_area_l = dic["server_param"]["catchable_area_l "]
        self._catchable_area_w = dic["server_param"]["catchable_area_w "]
        self._ckick_margin = dic["server_param"]["ckick_margin "]
        self._clang_advice_win = dic["server_param"]["clang_advice_win "]
        self._clang_define_win = dic["server_param"]["clang_define_win "]
        self._clang_del_win = dic["server_param"]["clang_del_win "]
        self._clang_info_win = dic["server_param"]["clang_info_win "]
        self._clang_mess_delay = dic["server_param"]["clang_mess_delay "]
        self._clang_mess_per_cycle = dic["server_param"]["clang_mess_per_cycle "]
        self._clang_meta_win = dic["server_param"]["clang_meta_win "]
        self._clang_rule_win = dic["server_param"]["clang_rule_win "]
        self._clang_win_size = dic["server_param"]["clang_win_size "]
        self._coach = dic["server_param"]["coach "]
        self._coach_port = dic["server_param"]["coach_port "]
        self._coach_w_referee = dic["server_param"]["coach_w_referee "]
        self._control_radius = dic["server_param"]["control_radius "]
        self._dash_power_rate = dic["server_param"]["dash_power_rate "]
        self._drop_ball_time = dic["server_param"]["drop_ball_time "]
        self._effort_dec = dic["server_param"]["effort_dec "]
        self._effort_dec_thr = dic["server_param"]["effort_dec_thr "]
        self._effort_inc = dic["server_param"]["effort_inc "]
        self._effort_inc_thr = dic["server_param"]["effort_inc_thr "]
        self._effort_init = dic["server_param"]["effort_init "]
        self._effort_min = dic["server_param"]["effort_min "]
        self._forbid_kick_off_offside = dic["server_param"]["forbid_kick_off_offside "]
        self._free_kick_faults = dic["server_param"]["free_kick_faults "]
        self._freeform_send_period = dic["server_param"]["freeform_send_period "]
        self._freeform_wait_period = dic["server_param"]["freeform_wait_period "]
        self._fullstate_l = dic["server_param"]["fullstate_l "]
        self._fullstate_r = dic["server_param"]["fullstate_r "]
        self._game_log_compression = dic["server_param"]["game_log_compression "]
        self._game_log_dated = dic["server_param"]["game_log_dated "]
        self._game_log_dir = dic["server_param"]["game_log_dir "]
        self._game_log_fixed = dic["server_param"]["game_log_fixed "]
        self._game_log_fixed_name = dic["server_param"]["game_log_fixed_name "]
        self._game_log_version = dic["server_param"]["game_log_version "]
        self._game_logging = dic["server_param"]["game_logging "]
        self._goal_width = dic["server_param"]["goal_width "]
        self._goalie_max_moves = dic["server_param"]["goalie_max_moves "]
        self._half_time = dic["server_param"]["half_time "]
        self._hear_decay = dic["server_param"]["hear_decay "]
        self._hear_inc = dic["server_param"]["hear_inc "]
        self._hear_max = dic["server_param"]["hear_max "]
        self._inertia_moment = dic["server_param"]["inertia_moment "]
        self._kick_power_rate = dic["server_param"]["kick_power_rate "]
        self._kick_rand = dic["server_param"]["kick_rand "]
        self._kick_rand_factor_l = dic["server_param"]["kick_rand_factor_l "]
        self._kick_rand_factor_r = dic["server_param"]["kick_rand_factor_r "]
        self._kickable_margin = dic["server_param"]["kickable_margin "]
        self._landmark_file = dic["server_param"]["landmark_file "]
        self._log_date_format = dic["server_param"]["log_date_format "]
        self._log_times = dic["server_param"]["log_times "]
        self._max_goal_kicks = dic["server_param"]["max_goal_kicks "]
        self._maxmoment = dic["server_param"]["maxmoment "]
        self._maxneckang = dic["server_param"]["maxneckang "]
        self._maxneckmoment = dic["server_param"]["maxneckmoment "]
        self._maxpower = dic["server_param"]["maxpower "]
        self._minmoment = dic["server_param"]["minmoment "]
        self._minneckang = dic["server_param"]["minneckang "]
        self._minneckmoment = dic["server_param"]["minneckmoment "]
        self._minpower = dic["server_param"]["minpower "]
        self._offside_active_area_size = dic["server_param"]["offside_active_area_size "]
        self._offside_kick_margin = dic["server_param"]["offside_kick_margin "]
        self._olcoach_port = dic["server_param"]["olcoach_port "]
        self._old_coach_hear = dic["server_param"]["old_coach_hear "]
        self._player_accel_max = dic["server_param"]["player_accel_max "]
        self._player_decay = dic["server_param"]["player_decay "]
        self._player_rand = dic["server_param"]["player_rand "]
        self._player_size = dic["server_param"]["player_size "]
        self._player_speed_max = dic["server_param"]["player_speed_max "]
        self._player_weight = dic["server_param"]["player_weight "]
        self._point_to_ban = dic["server_param"]["point_to_ban "]
        self._point_to_duration = dic["server_param"]["point_to_duration "]
        self._port = dic["server_param"]["port "]
        self._prand_factor_l = dic["server_param"]["prand_factor_l "]
        self._prand_factor_r = dic["server_param"]["prand_factor_r "]
        self._profile = dic["server_param"]["profile "]
        self._proper_goal_kicks = dic["server_param"]["proper_goal_kicks "]
        self._quantize_step = dic["server_param"]["quantize_step "]
        self._quantize_step_l = dic["server_param"]["quantize_step_l "]
        self._record_messages = dic["server_param"]["record_messages "]
        self._recover_dec = dic["server_param"]["recover_dec "]
        self._recover_dec_thr = dic["server_param"]["recover_dec_thr "]
        self._recover_min = dic["server_param"]["recover_min "]
        self._recv_step = dic["server_param"]["recv_step "]
        self._say_coach_cnt_max = dic["server_param"]["say_coach_cnt_max "]
        self._say_coach_msg_size = dic["server_param"]["say_coach_msg_size "]
        self._say_msg_size = dic["server_param"]["say_msg_size "]
        self._send_comms = dic["server_param"]["send_comms "]
        self._send_step = dic["server_param"]["send_step "]
        self._send_vi_step = dic["server_param"]["send_vi_step "]
        self._sense_body_step = dic["server_param"]["sense_body_step "]
        self._simulator_step = dic["server_param"]["simulator_step "]
        self._slow_down_factor = dic["server_param"]["slow_down_factor "]
        self._slowness_on_top_for_left_team = dic["server_param"]["slowness_on_top_for_left_team "]
        self._slowness_on_top_for_right_team = dic["server_param"]["slowness_on_top_for_right_team "]
        self._stamina_inc_max = dic["server_param"]["stamina_inc_max "]
        self._stamina_max = dic["server_param"]["stamina_max "]
        self._start_goal_l = dic["server_param"]["start_goal_l "]
        self._start_goal_r = dic["server_param"]["start_goal_r "]
        self._stopped_ball_vel = dic["server_param"]["stopped_ball_vel "]
        self._synch_micro_sleep = dic["server_param"]["synch_micro_sleep "]
        self._synch_mode = dic["server_param"]["synch_mode "]
        self._synch_offset = dic["server_param"]["synch_offset "]
        self._tackle_back_dist = dic["server_param"]["tackle_back_dist "]
        self._tackle_cycles = dic["server_param"]["tackle_cycles "]
        self._tackle_dist = dic["server_param"]["tackle_dist "]
        self._tackle_exponent = dic["server_param"]["tackle_exponent "]
        self._tackle_power_rate = dic["server_param"]["tackle_power_rate "]
        self._tackle_width = dic["server_param"]["tackle_width "]
        self._team_actuator_noise = dic["server_param"]["team_actuator_noise "]
        self._text_log_compression = dic["server_param"]["text_log_compression "]
        self._text_log_dated = dic["server_param"]["text_log_dated "]
        self._text_log_dir = dic["server_param"]["text_log_dir "]
        self._text_log_fixed = dic["server_param"]["text_log_fixed "]
        self._text_log_fixed_name = dic["server_param"]["text_log_fixed_name "]
        self._text_logging = dic["server_param"]["text_logging "]
        self._use_offside = dic["server_param"]["use_offside "]
        self._verbose = dic["server_param"]["verbose "]
        self._visible_angle = dic["server_param"]["visible_angle "]
        self._visible_distance = dic["server_param"]["visible_distance "]
        self._wind_ang = dic["server_param"]["wind_ang "]
        self._wind_dir = dic["server_param"]["wind_dir "]
        self._wind_force = dic["server_param"]["wind_force "]
        self._wind_none = dic["server_param"]["wind_none "]
        self._wind_rand = dic["server_param"]["wind_rand "]
        self._wind_random = dic["server_param"]["wind_random "]

    def parse(self, message):
        pass